# Generated by Django 4.1.1 on 2022-10-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=30, unique=True)),
                ('race', models.CharField(choices=[('1', 'Human'), ('2', 'Dwarf'), ('3', 'Elf'), ('4', 'Ork')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CitySuffix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=30, unique=True)),
                ('race', models.CharField(choices=[('1', 'Human'), ('2', 'Dwarf'), ('3', 'Elf'), ('4', 'Ork')], max_length=1)),
            ],
        ),
    ]
