# Generated by Django 4.1.1 on 2022-10-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_race_alter_cityprefix_race_alter_citysuffix_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Tavern', 'Tavern'), ('Inn', 'Inn'), ('Blacksmith', 'Blacksmith'), ('Tailor', 'Tailor'), ('Jeweler', 'Jeweler'), ("Musician's Shop", "Musician's Shop"), ("Weapon's Vendor", "Weapon's Vendor"), ('Armorer', 'Armorer'), ('Potion Shop', 'Potion Shop')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VillagerLastName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, unique=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.race')),
            ],
        ),
        migrations.CreateModel(
            name='VillagerFirstName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, unique=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.race')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSuffix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=30, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=30, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.business')),
            ],
        ),
    ]
