# Generated by Django 4.1.1 on 2022-11-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_businessinventory_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillagerNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, unique=True)),
                ('last_name', models.CharField(max_length=30, unique=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.race')),
            ],
        ),
        migrations.RemoveField(
            model_name='villagerlastname',
            name='race',
        ),
        migrations.DeleteModel(
            name='VillagerFirstName',
        ),
        migrations.DeleteModel(
            name='VillagerLastName',
        ),
    ]
