# Generated by Django 4.1.1 on 2022-11-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_villagerfirstnames_villagerlastnames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npctraits',
            name='type',
            field=models.CharField(choices=[('Common', 'Common'), ('Official', 'Official'), ('Guard', 'Guard'), ('Business', 'Business')], default='Common', max_length=50),
        ),
    ]
