# Generated by Django 4.1.1 on 2022-11-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_npctraits_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.CharField(choices=[('Tavern', 'Tavern'), ('Inn', 'Inn'), ('Blacksmith', 'Blacksmith'), ('Tailor', 'Tailor'), ('Jeweler', 'Jeweler'), ("Musician's Shop", "Musician's Shop"), ("Weapon's Vendor", "Weapon's Vendor"), ('Armorer', 'Armorer'), ('Potion Shop', 'Potion Shop'), ('General Goods', 'General Goods'), ('Pet Shop', 'Pet Shop'), ('Map Maker', 'Map Maker'), ('Bank', 'Bank'), ('Library', 'Library')], max_length=30),
        ),
        migrations.AlterField(
            model_name='npctraits',
            name='type',
            field=models.CharField(choices=[('Common', 'Common'), ('Official', 'Official'), ('Guard', 'Guard'), ('Business', 'Business'), ('Professional', 'Professional')], default='Common', max_length=50),
        ),
        migrations.CreateModel(
            name='PointsOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.race')),
            ],
        ),
    ]
