# Generated by Django 4.1.1 on 2022-11-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_alter_business_type_alter_npctraits_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagerfirstnames',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=30),
        ),
    ]
