# Generated by Django 4.1.1 on 2022-12-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_villagerfirstnames_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
