# Generated by Django 4.1.1 on 2022-09-28 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='Units', max_length=30),
        ),
        migrations.AddField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reciperequirements',
            name='quantity_needed',
            field=models.FloatField(default=0.0),
        ),
    ]
