# Generated by Django 4.1.1 on 2022-09-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ingredient_unit_purchase_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirements',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='reciperequirements',
            name='ingredient',
            field=models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
