# Generated by Django 4.1.1 on 2022-10-05 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_reciperequirements_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_item_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='reciperequirements',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient'),
        ),
    ]
