# Generated by Django 4.1.1 on 2022-10-08 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_menuitem_menu_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
