# Generated by Django 4.1.1 on 2022-10-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_menuitem_item_price_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperequirements',
            old_name='menu_item',
            new_name='menu_item_id',
        ),
    ]
