# Generated by Django 4.1.1 on 2022-10-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_menu_item_reciperequirements_menu_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirements',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient'),
        ),
    ]
